--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0="5735932";local v1=12 * (44 + 16) * (85 -25) ;local v2="FNAF_COOP_FNAF2AUTO_V2_KeyTime.txt";local v3="https://raw.githubusercontent.com/luissierramcdonalds4/FNAF-COOP-Ultimate-Hub/refs/heads/main/fnaf2autov2.lua";local v4=game:GetService("HttpService");local function v5() if isfile(v2) then local v14=1065 -(68 + 997) ;local v15;local v16;while true do if (v14==(0 -0)) then v15,v16=pcall(function() return tonumber(readfile(v2));end);if (v15 and v16) then return v16;end break;end end end return 1270 -(226 + 1044) ;end local function v6() writefile(v2,tostring(os.time()));end local function v7() return (os.time() -v5())<v1 ;end local function v8() loadstring(game:HttpGet(v3,true))();end local v9=loadstring(game:HttpGet("https://sirius.menu/rayfield"))();if v7() then v9:Notify({Title="Access Granted",Content="Key still valid for this script. Launching...",Duration=21 -16 });task.wait(0.5 -0 );v9:Destroy();v8();return;end local v10=v9:CreateWindow({Name="FNAF: COOP Auto System",LoadingTitle="FNAF: COOP",LoadingSubtitle="Key Verification",KeySystem=false});local v11=v10:CreateTab("Key System",4483362575 -(32 + 85) );local v12="";v11:CreateInput({Name="Enter Access Key",PlaceholderText="Numbers only",RemoveTextAfterFocusLost=false,Callback=function(v13) v12=v13;end});v11:CreateButton({Name="Submit Key",Callback=function() if (v12==v0) then local v17=0 + 0 ;while true do if (v17==(0 -0)) then v6();v9:Notify({Title="Success",Content="Key accepted. Launching script...",Duration=2 + 3 });v17=958 -(892 + 65) ;end if (v17==(2 -1)) then task.wait(0.5 -0 );v9:Destroy();v17=3 -1 ;end if (v17==(1 + 1)) then v8();break;end end else v9:Notify({Title="Invalid Key",Content="Incorrect key. Please try again.",Duration=354 -(87 + 263) });end end});v11:CreateButton({Name="Get Key (Join Discord)",Callback=function() if setclipboard then setclipboard("https://discord.gg/bnPVDvpnJa");v9:Notify({Title="Copied",Content="Discord invite copied to clipboard.",Duration=184 -(67 + 113) });else v9:Notify({Title="Error",Content="Clipboard not supported by your executor.",Duration=4});end end});v11:CreateParagraph({Title="Notice",Content="This key system is separate from other scripts.\n\n"   .. "You must re-enter the key every 12 hours\n"   .. "specifically for this script." });
