--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0="5735932";local v1=(1265 -(976 + 277)) * (1057 -(915 + 82)) * (169 -109) ;local v2="FNAF_COOP_KeyTime.txt";local v3="https://raw.githubusercontent.com/luissierramcdonalds4/FNAF-COOP-Ultimate-Hub/refs/heads/main/loader.lua";local v4=game:GetService("HttpService");local function v5() local v13=957 -(892 + 65) ;while true do if (v13==(0 -0)) then if isfile(v2) then local v17=0 -0 ;local v18;local v19;while true do if (0==v17) then v18,v19=pcall(function() return tonumber(readfile(v2));end);if (v18 and v19) then return v19;end break;end end end return 0 -0 ;end end end local function v6() writefile(v2,tostring(os.time()));end local function v7() return (os.time() -v5())<v1 ;end local function v8() loadstring(game:HttpGet(v3))();end local v9=loadstring(game:HttpGet("https://sirius.menu/rayfield"))();if v7() then local v15=350 -(87 + 263) ;while true do if (v15==(181 -(67 + 113))) then v9:Destroy();v8();v15=2;end if ((2 + 0)==v15) then return;end if (v15==(0 -0)) then v9:Notify({Title="Access Granted",Content="Key still valid. Launching hub...",Duration=5 + 0 });task.wait(791.5 -(368 + 423) );v15=3 -2 ;end end end local v10=v9:CreateWindow({Name="FNAF: COOP Ultimate Script",LoadingTitle="FNAF: COOP",LoadingSubtitle="Key System",KeySystem=false});local v11=v10:CreateTab("Key System",4483363988 -(568 + 962) );local v12="";v11:CreateInput({Name="Enter Access Key",PlaceholderText="Numbers only",RemoveTextAfterFocusLost=false,Callback=function(v14) v12=v14;end});v11:CreateButton({Name="Submit Key",Callback=function() if (v12==v0) then local v16=18 -(10 + 8) ;while true do if (v16==(0 -0)) then v6();v9:Notify({Title="Success",Content="Key accepted. Launching hub...",Duration=15 -10 });v16=2 -1 ;end if (v16==(1 + 0)) then task.wait(0.5);v9:Destroy();v16=1956 -(508 + 1446) ;end if (v16==2) then v8();break;end end else v9:Notify({Title="Invalid Key",Content="Incorrect key. Please try again.",Duration=442 -(145 + 293) });end end});v11:CreateButton({Name="Get Key (Join Discord)",Callback=function() if setclipboard then setclipboard("https://discord.gg/bnPVDvpnJa");v9:Notify({Title="Copied",Content="Discord server link copied to clipboard.",Duration=434 -(44 + 386) });else v9:Notify({Title="Error",Content="Your executor does not support clipboard copying.",Duration=3 + 1 });end end});v11:CreateParagraph({Title="Notice",Content="The access key is required every 12 hours.\n\n"   .. "If your key expires, the loader will reappear\n"   .. "and you must enter the key again." });
