--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0="5735932";local v1=(34 -22) * (628 -(367 + 201)) * (987 -(214 + 713)) ;local v2="FNAF_COOP_KeyTime.txt";local v3="https://raw.githubusercontent.com/luissierramcdonalds4/FNAF-COOP-Ultimate-Hub/refs/heads/main/loader.lua";local v4=game:GetService("HttpService");local function v5() local v13=0 + 0 ;while true do if (v13==0) then if isfile(v2) then local v17,v18=pcall(function() return tonumber(readfile(v2));end);if (v17 and v18) then return v18;end end return 0 + 0 ;end end end local function v6() writefile(v2,tostring(os.time()));end local function v7() return (os.time() -v5())<v1 ;end local function v8() loadstring(game:HttpGet(v3))();end local v9=loadstring(game:HttpGet("https://sirius.menu/rayfield"))();if v7() then local v15=877 -(282 + 595) ;while true do if (v15==(182 -(67 + 113))) then return;end if (v15==(1638 -(1523 + 114))) then v9:Destroy();v8();v15=4 -2 ;end if (v15==(0 + 0)) then v9:Notify({Title="Access Granted",Content="Key still valid. Launching hub...",Duration=5 + 0 });task.wait(0.5 -0 );v15=1066 -(68 + 997) ;end end end local v10=v9:CreateWindow({Name="FNAF: COOP Ultimate Script",LoadingTitle="FNAF: COOP",LoadingSubtitle="Key System",KeySystem=false});local v11=v10:CreateTab("Key System",4483363728 -(226 + 1044) );local v12="";v11:CreateInput({Name="Enter Access Key",PlaceholderText="Numbers only",RemoveTextAfterFocusLost=false,Callback=function(v14) v12=v14;end});v11:CreateButton({Name="Submit Key",Callback=function() if (v12==v0) then v6();v9:Notify({Title="Success",Content="Key accepted. Launching hub...",Duration=21 -16 });task.wait(117.5 -(32 + 85) );v9:Destroy();v8();else v9:Notify({Title="Invalid Key",Content="Incorrect key. Please try again.",Duration=3 + 1 });end end});v11:CreateButton({Name="Get Key (Join Discord)",Callback=function() if setclipboard then local v16=0 + 0 ;while true do if (v16==(0 + 0)) then setclipboard("https://discord.gg/bnPVDvpnJa");v9:Notify({Title="Copied",Content="Discord server link copied to clipboard.",Duration=11 -7 });break;end end else v9:Notify({Title="Error",Content="Your executor does not support clipboard copying.",Duration=961 -(892 + 65) });end end});v11:CreateParagraph({Title="Notice",Content="The access key is required every 2 hours.\n\n"   .. "If your key expires, the loader will reappear\n"   .. "and you must enter the key again." });
