--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0="5735932";local v1=(237 -(23 + 212)) * (25 + 35) * (1906 -(1228 + 618)) ;local v2="FNAF_COOP_KeyTime.txt";local v3="https://raw.githubusercontent.com/luissierramcdonalds4/FNAF-COOP-Ultimate-Hub/refs/heads/main/loader.lua";local v4=game:GetService("HttpService");local function v5() local v13=0;while true do if ((0 -0)==v13) then if isfile(v2) then local v18=0 -0 ;local v19;local v20;while true do if (v18==(952 -(802 + 150))) then v19,v20=pcall(function() return tonumber(readfile(v2));end);if (v19 and v20) then return v20;end break;end end end return 0 -0 ;end end end local function v6() writefile(v2,tostring(os.time()));end local function v7() return (os.time() -v5())<v1 ;end local function v8() loadstring(game:HttpGet(v3))();end local v9=loadstring(game:HttpGet("https://sirius.menu/rayfield"))();if v7() then local v15=0 -0 ;while true do if (v15==2) then return;end if (v15==(1 + 0)) then v9:Destroy();v8();v15=2;end if (v15==(997 -(915 + 82))) then v9:Notify({Title="Access Granted",Content="Key still valid. Launching hub...",Duration=14 -9 });task.wait(0.5);v15=1;end end end local v10=v9:CreateWindow({Name="FNAF: COOP Ultimate Script",LoadingTitle="FNAF: COOP",LoadingSubtitle="Key System",KeySystem=false});local v11=v10:CreateTab("Key System",4483362458 -0 );local v12="";v11:CreateInput({Name="Enter Access Key",PlaceholderText="Numbers only",RemoveTextAfterFocusLost=false,Callback=function(v14) v12=v14;end});v11:CreateButton({Name="Submit Key",Callback=function() if (v12==v0) then local v16=1187 -(1069 + 118) ;while true do if (v16==(4 -2)) then v8();break;end if (v16==(0 -0)) then v6();v9:Notify({Title="Success",Content="Key accepted. Launching hub...",Duration=1 + 4 });v16=1 -0 ;end if (v16==1) then task.wait(0.5 + 0 );v9:Destroy();v16=793 -(368 + 423) ;end end else v9:Notify({Title="Invalid Key",Content="Incorrect key. Please try again.",Duration=12 -8 });end end});v11:CreateButton({Name="Get Key (Join Discord)",Callback=function() if setclipboard then local v17=18 -(10 + 8) ;while true do if (v17==0) then setclipboard("https://discord.gg/gzmraP5rab");v9:Notify({Title="Copied",Content="Discord server link copied to clipboard.",Duration=15 -11 });break;end end else v9:Notify({Title="Error",Content="Your executor does not support clipboard copying.",Duration=446 -(416 + 26) });end end});v11:CreateParagraph({Title="Notice",Content="The access key is required every 2 hours.\n\n"   .. "If your key expires, the loader will reappear\n"   .. "and you must enter the key again." });
