--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0="Key2";local v1=(1 + 11) * (143 -83) * 60 ;local v2="ProjectNightShift_KeyTime.txt";local v3="https://pastebin.com/raw/pXmjxjHP";local v4="https://discord.gg/XPzgkHKW7u";local v5=game:GetService("HttpService");local function v6() local v14=0 -0 ;while true do if (v14==(0 -0)) then if isfile(v2) then local v18=0;local v19;local v20;while true do if (v18==(350 -(87 + 263))) then v19,v20=pcall(function() return tonumber(readfile(v2));end);if (v19 and v20) then return v20;end break;end end end return 0;end end end local function v7() writefile(v2,tostring(os.time()));end local function v8() return (os.time() -v6())<v1 ;end local function v9() loadstring(game:HttpGet(v3,true))();end local v10=loadstring(game:HttpGet("https://sirius.menu/rayfield"))();if v8() then v10:Notify({Title="Access Granted",Content="Key still valid. Launching Project NightShift...",Duration=185 -(67 + 113) });task.wait(0.5 + 0 );v10:Destroy();v9();return;end local v11=v10:CreateWindow({Name="Project NightShift",LoadingTitle="Project NightShift",LoadingSubtitle="Key Verification",KeySystem=false});local v12=v11:CreateTab("Key System",5354880865 -871518407 );local v13="";v12:CreateInput({Name="Enter Access Key",PlaceholderText="Enter key here",RemoveTextAfterFocusLost=false,Callback=function(v15) v13=v15;end});v12:CreateButton({Name="Submit Key",Callback=function() if (v13==v0) then local v16=0 + 0 ;while true do if (v16==(3 -2)) then task.wait(952.5 -(802 + 150) );v10:Destroy();v16=2;end if (v16==(0 -0)) then v7();v10:Notify({Title="Success",Content="Key accepted. Launching Project NightShift...",Duration=5});v16=1 -0 ;end if (v16==(2 + 0)) then v9();break;end end else v10:Notify({Title="Invalid Key",Content="Incorrect key. Please try again.",Duration=1001 -(915 + 82) });end end});v12:CreateButton({Name="📋 Get Key (Join Discord)",Callback=function() if setclipboard then local v17=0 -0 ;while true do if (v17==0) then setclipboard(v4);v10:Notify({Title="Copied",Content="Discord invite copied to clipboard.",Duration=4});break;end end else v10:Notify({Title="Error",Content="Clipboard not supported by your executor.",Duration=4});end end});v12:CreateParagraph({Title="Notice",Content="This key system is unique to Afton-Robotics.\n\n"   .. "💰 Earn ~$60 per minute completely automatically\n"   .. "⏱ ~18,000 in 6 hours with Janitor\n\n"   .. "You must re-enter the key every 12 hours\n"   .. "for this script only." });
